### ISSUE TITLE
On running rebuild after cloning 

### ISSUE THREAD

**Issue by Dozzergeeky** [sukhmancs/nixos-configs#81]
nixos-rebuild switch --flake

error: flake 'git+file:///etc/nixos/nixos-titus/system/nixos-configs' does not provide attribute 'packages.x86_64-linux. nixosConfigurations."nixos-studio".config.systes.build.nixos-rebuild','legacyPackages.x86_64-linux.nixosConfigurations "nixos-studio".config.systes.build.nixos-rebuild' or 'nixosConfigurations."nixos-studio".config.system.build.nixos-rebuild'

**Comment by sukhmancs** [comment]
You are not using the full comand. I have these hosts available milkyway, triangulum, andromeda:
```
nixos-rebuild switch --flake .#milkyway
```

**Comment by Dozzergeeky** [comment]
error: flake 'git+file:///root/.config/nixos-configs' does not provide attribute 'packages.x86_64-11nux.nixosConfigurations."andromeda".c onfig.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations. "andromeda".config.system.build.nixos-rebuild' or 'ni

xosConfigurations. "andromeda".config.system.build.nixos-rebuild'

Inix-shell:"/.config/nixos-configs]# nixos-rebuild switch-flake andromeda

path /root/.config/nixos-configs/.andromeda' does not contain a 'flake.nix', searching up

error: getting status of /root/.config/nixos-configs/.andromeda': No such file or directory

Inix-shell:"/.config/nixos-configs]# nixos-rebuild switch-flake #landromeda

error: flake 'git+file:///root/.config/nixos-configs' does not provide attribute 'packages.x86 54-1inux.nixosConfigurations. "andromeda".c onfig.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations. "andromeda".config.system.build.nixos-rebuild' or 'ni

xosConfigurations, "andromeda".config.system.build.nixos-rebuild

[nix-shell:"/.config/nixos-configs]# nixos-rebuild switch-flake#messier

error: flake 'git+file:///root/.config/nixos-configs' does not provide attribute 'packages.x86_64-linux.nixosConfigurat lons. "messler".con fig.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations. "messler".config.system.build.nixos-rebuild!

[
IMG_20240918_112314_1.jpg](https://github.com/user-attachments/assets/4cf23c23-c73c-446c-bfdd-1cc07189f2d1)
