### ISSUE TITLE
(andromeda) build error: agenix identity issues rendering the system unbootable

### ISSUE THREAD

**Issue by builtbyvys** [sukhmancs/nixos-configs#82]
Hello,
I'd like to start this off by saying amazing config! I'd love to use this setup. I have an issue that is causing this to be unusuable for me when it comes to the secrets (agenix). When building the andromeda system, when it comes to finally building the system, I seem to get a lot of issues regarding unable to find a compatible identity. When I attempt to boot afterward, I seem to get a huge backtrace after a second of seeing the boot logo.

What can I do to resolve this?
Thanks in advance!

**Comment by sukhmancs** [comment]
I no longer maintain andromeda host. Try to use milkyway. Milkyway and andromeda are not that different. milkyway is for laptop will have tlp enabled.
